spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: 'true'
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
    show-sql: 'true'
  security:
    filter:
      order: '10'
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    username: root
    url: jdbc:mariadb://0.0.0.0:3307/cocktailshop
server:
  error:
    include-message: always
    include-stacktrace: never
    include-exception: false
logging:
  level:
    org:
      springframework:
        security: DEBUG
        hibernate: DEBUG
        jdbc: DEBUG
        jpa: DEBUG
        transaction: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG
constants:
  jwt:
    tokenprefix: "Bearer "
    secret: "very secure secret" # TODO Improve
    expiration:
      access_token: 600000 # 10 minutes
      refresh_token: 3600000 # 1 hour
    uriwhitelist:
      - "/login"
      - "/register"
      - "/api/v1/auth/forgotten"
      - "/api/v1/auth/refresh"
      - "/api-docs"
      - "/swagger-resources/"
      - "/swagger-ui"
    claims:
      roles: "rls"