## MariaDB instance bound to port 3307 on the host. Data is persisted.
## PhpMyAdmin instance bound to port 8000. Use root as user and password.

version: '3.1'

services:
  db:
    image: mariadb:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cocktailshop
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db: